name: Auto Commit
on:
  workflow_dispatch:
  schedule:
    - cron: '9 0 12 6 *'
    - cron: '59 5 12 6 *'
    - cron: '22 8 12 6 *'
    - cron: '2 13 12 6 *'
    - cron: '47 16 12 6 *'

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: true
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Set Git Identity
        run: |
          git config --global user.name "Harsh Vekariya"
          git config --global user.email "harshvekariya203@gmail.com"

      - name: Create Single Change
        run: |
          node ./auto_commit_script.js
          git add .
          git commit -m "Auto commit [$(date -u)]"
          git push